const COUNTRY_ALIASES = {
  brazil: { name: "Brazil", code: "BR" },
  brasil: { name: "Brazil", code: "BR" },
  "united states": { name: "United States", code: "US" },
  usa: { name: "United States", code: "US" },
  us: { name: "United States", code: "US" },
  "estados unidos": { name: "United States", code: "US" },
  eeuu: { name: "United States", code: "US" },
  eua: { name: "United States", code: "US" },
  mexico: { name: "Mexico", code: "MX" },
  canada: { name: "Canada", code: "CA" },
  argentina: { name: "Argentina", code: "AR" },
  chile: { name: "Chile", code: "CL" },
  colombia: { name: "Colombia", code: "CO" },
  peru: { name: "Peru", code: "PE" },
  venezuela: { name: "Venezuela", code: "VE" },
  "dominican republic": { name: "Dominican Republic", code: "DO" },
  dominicana: { name: "Dominican Republic", code: "DO" },
  "puerto rico": { name: "Puerto Rico", code: "PR" },
  ecuador: { name: "Ecuador", code: "EC" },
  uruguay: { name: "Uruguay", code: "UY" },
  paraguay: { name: "Paraguay", code: "PY" },
  bolivia: { name: "Bolivia", code: "BO" },
  "costa rica": { name: "Costa Rica", code: "CR" },
  panama: { name: "Panama", code: "PA" },
  guatemala: { name: "Guatemala", code: "GT" },
  honduras: { name: "Honduras", code: "HN" },
  "el salvador": { name: "El Salvador", code: "SV" },
  nicaragua: { name: "Nicaragua", code: "NI" },
  cuba: { name: "Cuba", code: "CU" },
  jamaica: { name: "Jamaica", code: "JM" },
  haiti: { name: "Haiti", code: "HT" },
  "trinidad and tobago": { name: "Trinidad and Tobago", code: "TT" },
  guyana: { name: "Guyana", code: "GY" },
  suriname: { name: "Suriname", code: "SR" },
  belize: { name: "Belize", code: "BZ" },
  uk: { name: "United Kingdom", code: "GB" },
  "united kingdom": { name: "United Kingdom", code: "GB" },
  england: { name: "United Kingdom", code: "GB" },
  germany: { name: "Germany", code: "DE" },
  france: { name: "France", code: "FR" },
  spain: { name: "Spain", code: "ES" },
  portugal: { name: "Portugal", code: "PT" },
  italy: { name: "Italy", code: "IT" },
  poland: { name: "Poland", code: "PL" },
  netherlands: { name: "Netherlands", code: "NL" },
  sweden: { name: "Sweden", code: "SE" },
  norway: { name: "Norway", code: "NO" },
  denmark: { name: "Denmark", code: "DK" },
  finland: { name: "Finland", code: "FI" },
  russia: { name: "Russia", code: "RU" },
  romania: { name: "Romania", code: "RO" },
  czechia: { name: "Czech Republic", code: "CZ" },
  hungary: { name: "Hungary", code: "HU" },
  greece: { name: "Greece", code: "GR" },
  ukraine: { name: "Ukraine", code: "UA" },
  belgium: { name: "Belgium", code: "BE" },
  switzerland: { name: "Switzerland", code: "CH" },
  austria: { name: "Austria", code: "AT" },
  ireland: { name: "Ireland", code: "IE" },
  croatia: { name: "Croatia", code: "HR" },
  serbia: { name: "Serbia", code: "RS" },
  bulgaria: { name: "Bulgaria", code: "BG" },
  slovakia: { name: "Slovakia", code: "SK" },
  slovenia: { name: "Slovenia", code: "SI" },
  lithuania: { name: "Lithuania", code: "LT" },
  latvia: { name: "Latvia", code: "LV" },
  estonia: { name: "Estonia", code: "EE" },
  iceland: { name: "Iceland", code: "IS" },
  luxembourg: { name: "Luxembourg", code: "LU" },
  malta: { name: "Malta", code: "MT" },
  cyprus: { name: "Cyprus", code: "CY" },
  albania: { name: "Albania", code: "AL" },
  "north macedonia": { name: "North Macedonia", code: "MK" },
  montenegro: { name: "Montenegro", code: "ME" },
  bosnia: { name: "Bosnia and Herzegovina", code: "BA" },
  kosovo: { name: "Kosovo", code: "XK" },
  moldova: { name: "Moldova", code: "MD" },
  belarus: { name: "Belarus", code: "BY" },
  georgia: { name: "Georgia", code: "GE" },
  japan: { name: "Japan", code: "JP" },
  china: { name: "China", code: "CN" },
  "south korea": { name: "South Korea", code: "KR" },
  "north korea": { name: "North Korea", code: "KP" },
  india: { name: "India", code: "IN" },
  philippines: { name: "Philippines", code: "PH" },
  indonesia: { name: "Indonesia", code: "ID" },
  turkey: { name: "Turkey", code: "TR" },
  australia: { name: "Australia", code: "AU" },
  "new zealand": { name: "New Zealand", code: "NZ" },
  singapore: { name: "Singapore", code: "SG" },
  malaysia: { name: "Malaysia", code: "MY" },
  thailand: { name: "Thailand", code: "TH" },
  vietnam: { name: "Vietnam", code: "VN" },
  taiwan: { name: "Taiwan", code: "TW" },
  pakistan: { name: "Pakistan", code: "PK" },
  bangladesh: { name: "Bangladesh", code: "BD" },
  "sri lanka": { name: "Sri Lanka", code: "LK" },
  nepal: { name: "Nepal", code: "NP" },
  myanmar: { name: "Myanmar", code: "MM" },
  cambodia: { name: "Cambodia", code: "KH" },
  laos: { name: "Laos", code: "LA" },
  mongolia: { name: "Mongolia", code: "MN" },
  kazakhstan: { name: "Kazakhstan", code: "KZ" },
  uzbekistan: { name: "Uzbekistan", code: "UZ" },
  fiji: { name: "Fiji", code: "FJ" },
  brunei: { name: "Brunei", code: "BN" },
  maldives: { name: "Maldives", code: "MV" },
  israel: { name: "Israel", code: "IL" },
  "saudi arabia": { name: "Saudi Arabia", code: "SA" },
  uae: { name: "United Arab Emirates", code: "AE" },
  "united arab emirates": { name: "United Arab Emirates", code: "AE" },
  iran: { name: "Iran", code: "IR" },
  iraq: { name: "Iraq", code: "IQ" },
  jordan: { name: "Jordan", code: "JO" },
  lebanon: { name: "Lebanon", code: "LB" },
  kuwait: { name: "Kuwait", code: "KW" },
  qatar: { name: "Qatar", code: "QA" },
  bahrain: { name: "Bahrain", code: "BH" },
  oman: { name: "Oman", code: "OM" },
  syria: { name: "Syria", code: "SY" },
  yemen: { name: "Yemen", code: "YE" },
  palestine: { name: "Palestine", code: "PS" },
  egypt: { name: "Egypt", code: "EG" },
  "south africa": { name: "South Africa", code: "ZA" },
  nigeria: { name: "Nigeria", code: "NG" },
  morocco: { name: "Morocco", code: "MA" },
  algeria: { name: "Algeria", code: "DZ" },
  tunisia: { name: "Tunisia", code: "TN" },
  kenya: { name: "Kenya", code: "KE" },
  ethiopia: { name: "Ethiopia", code: "ET" },
  ghana: { name: "Ghana", code: "GH" },
  senegal: { name: "Senegal", code: "SN" },
  cameroon: { name: "Cameroon", code: "CM" },
  "ivory coast": { name: "Ivory Coast", code: "CI" },
  tanzania: { name: "Tanzania", code: "TZ" },
  uganda: { name: "Uganda", code: "UG" },
  angola: { name: "Angola", code: "AO" },
  mozambique: { name: "Mozambique", code: "MZ" },
  zambia: { name: "Zambia", code: "ZM" },
  zimbabwe: { name: "Zimbabwe", code: "ZW" },
  libya: { name: "Libya", code: "LY" },
  sudan: { name: "Sudan", code: "SD" },
  namibia: { name: "Namibia", code: "NA" },
  botswana: { name: "Botswana", code: "BW" },
  madagascar: { name: "Madagascar", code: "MG" },
  congo: { name: "Congo", code: "CG" },
  "dr congo": { name: "DR Congo", code: "CD" },
};

function countryToFlag(countryCode) {
  if (!countryCode || countryCode.length !== 2) return "🏳️";
  return String.fromCodePoint(
    ...[...countryCode.toUpperCase()].map((character) => 0x1f1e6 + character.charCodeAt(0) - 65)
  );
}

function stripAccents(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

function resolveCountry(input) {
  if (!input) return null;
  const normalized = stripAccents(input.trim().toLowerCase());
  if (COUNTRY_ALIASES[normalized]) {
    const country = COUNTRY_ALIASES[normalized];
    return { name: country.name, code: country.code, flag: countryToFlag(country.code) };
  }
  for (const country of Object.values(COUNTRY_ALIASES)) {
    if (country.code.toLowerCase() === normalized) {
      return { name: country.name, code: country.code, flag: countryToFlag(country.code) };
    }
  }
  return null;
}

module.exports = { resolveCountry, countryToFlag };
